---
openapi: 3.0.0
info:
  title: Heart Attack Prediction
  description: A Model that will decided if given datapoints of a person are likely to have a heart attack
  contact:
    name: Ryan Herrington
  version: 0.0-oas3
servers:
- url: http://localhost:8080/
paths:
  /predict/{data}:
    get:
      tags:
      - CLASSIFY
      description: This is the input from the user, and should be sent in as an array to the model.
      operationId: model_file.predict
      parameters:
      - name: data
        in: path
        required: true
        style: simple
        explode: true
        schema:
          minItems: 1
          type: array
          items:
            type: number
      - name: metadata
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: boolean
      responses:
        "200":
          description: This is what returns the result of the prediction to the user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CLASSIFY'
        "500":
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CLASSIFY'
components:
  schemas:
    CLASSIFY:
      required:
      - model
      type: object
      properties:
        model:
          type: string
